### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by ChristophRaab** [Azure-Samples/azure-openai-terraform-deployment-sample#37]
## Description
---------------------------------------------------------------
I tried the example in this repository and was able to successfully apply the terraform. 
After that, i tried to run `terraform output -raw installation-script | bash` and my kube config is updated. However, i am unable to schedule the deployment afterwards and get the following error:
```
Unable to connect to the server: read tcp [fd8b:ac10:8700:110a:a05d:81a4:b075:a8a3]:58134->[fd8b:ac10:8700:7777::b92e:d45a]:80: wsarecv: An existing connection was forcibly closed by the remote host.
```
I am also unable to show all deployments, hence i assume there is something wrong with my vnet as described [here](https://learn.microsoft.com/en-us/azure/aks/hybrid/known-issues-installation). However, this should be a general problem of the example then, right? 

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
```

### Minimal steps to reproduce
>
Apply the example as in the readme. 

### Any log messages given by the failure
```
Unable to connect to the server: read tcp [fd8b:ac10:8700:110a:a05d:81a4:b075:a8a3]:58134->[fd8b:ac10:8700:7777::b92e:d45a]:80: wsarecv: An existing connection was forcibly closed by the remote host.
```
### Expected/desired behavior
The deployment should just be created and be accessible. 

### OS and Version?
> Windows 10

### Versions
> 
Kubectl Version:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/amd64"}
``` 
Terraform Versions:
```
Terraform v1.7.5
on windows_386
+ provider registry.terraform.io/azure/azapi v1.12.1
+ provider registry.terraform.io/azure/modtm v0.2.0
+ provider registry.terraform.io/hashicorp/azurerm v3.96.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5
``` 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zioproto** [comment]
It seems you have a network problem and `kubectl` cannot reach the cluster.

If you run `kubectl get nodes` you have the same problem ?

Do you have any firewall restriction that could prevent you from reaching the Kubernetes API ?

**Comment by ChristophRaab** [comment]
Yes, that seemed to be the problem. Thank you very much.
